name: Votifier
main: com.vexsoftware.votifier.Votifier
version: maven-version-number
description: A plugin that gets notified when votes are made for the server on toplists.
authors: [blakeman8192, Kramer, Ian]
api-version: 1.13+ # For those higher versions <3